repos:
- repo: local
  hooks:
  - id: end-of-file-fixer
    name: end-of-file-fixer
    language: system
    entry: end-of-file-fixer
    
  - id: check-added-large-files
    name: check-added-large-files
    language: system
    entry: check-added-large-files
    exclude: ^benchmarks/results/pytest/.*\.json$
    
  - id: mixed-line-ending
    name: mixed-line-ending
    language: system
    entry: mixed-line-ending
    args: [--fix=lf]
  
  - id: ruff-check
    name: ruff-check
    stages: [pre-commit]
    language: system
    entry: ruff check --fix --force-exclude
    types_or: [python, pyi]
  
  - id: ruff-format
    name: ruff-format
    stages: [pre-commit]
    language: system
    entry: ruff format --force-exclude
    types_or: [python, pyi]
    
  - id: jupyter-nb-clear-output
    name: jupyter-nb-clear-output
    files: \.ipynb$
    stages: [pre-commit]
    language: system
    entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
